server:
  port: 8080
  context-path: /api/v1

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:bank
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization:true:


